Домашнее задание урок 5
KTo1/python-faculty pull request #36
Opened 2022-02-16 15:45 UTC by KTo1

Домашнее задание урок 5

2022-03-28 07:39 UTC, Om1X requested changes

2022-03-28 07:39 UTC, Om1X commented on javascript-basic/lesson-05/homework/task-2.js
> +console.log('---------------------------------------------');
логика не должна "вываливаться" из объекта. Все что связано с работой корзины, должно находиться внутри объекта корзины.

2022-03-28 07:43 UTC, Om1X requested changes

2022-03-28 07:43 UTC, Om1X commented on javascript-basic/lesson-05/homework/task-2.js
> +            this.goods.push([id, name, count, price]);
список товаров корзины должен быть в виде массива объектов-товаров

2022-03-29 14:37 UTC, KTo1 commented on javascript-basic/lesson-05/homework/task-2.js
> +console.log('---------------------------------------------');
А можете уточнить, что именно вывалилось?) Что мне в объект поместить?

2022-03-29 14:37 UTC, KTo1 commented on javascript-basic/lesson-05/homework/task-2.js
> +            this.goods.push([id, name, count, price]);
Это я переделал

2022-03-31 15:22 UTC, merged