Домашнее задание урок 6
KTo1/python-faculty pull request #37
Opened 2022-02-21 15:21 UTC by KTo1

Домашнее задание урок 6

2022-03-28 07:46 UTC, Om1X requested changes

2022-03-28 07:46 UTC, Om1X commented on javascript-basic/lesson-06/homework/task-1.js
> +Catalog.add(3, 'good 3', ['img3_1.jpg', 'img3_2.jpg', 'img3_3.jpg'], 7, 16);
список товаров каталога должен быть в виде массива объектов-товаров

2022-03-28 07:46 UTC, Om1X commented on javascript-basic/lesson-06/homework/task-1.js
> +        goods: [],
список товаров корзины должен быть в виде массива объектов-товаров

2022-03-28 07:46 UTC, Om1X commented on javascript-basic/lesson-06/homework/task-1.js
> +        draw(){
отрисовку лучше сделать через шаблонные строки.

2022-03-28 07:46 UTC, Om1X commented on javascript-basic/lesson-06/homework/task-1.js
> +        draw(){
аналогично корзине, отрисовку лучше сделать через шаблонные строки.

2022-03-29 14:40 UTC, KTo1 commented on javascript-basic/lesson-06/homework/task-1.js
> +        draw(){
А можете подробнее рассказать? Имеется ввиду не через DOM? Т.е. в файле html сделать какие-то маркеры? Что за шаблонные строки?

2022-03-29 14:40 UTC, KTo1 commented on javascript-basic/lesson-06/homework/task-1.js
> +Catalog.add(3, 'good 3', ['img3_1.jpg', 'img3_2.jpg', 'img3_3.jpg'], 7, 16);
сделал ввиде массива, но возможно не верно)

2022-03-31 15:23 UTC, merged